const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const root = __dirname;
const corePath = path.join(root, "core.lua");
const nativeUiPath = path.join(root, "native_ui.lua");
const payloadDirectory = path.join(root, "payload");
const loaderPath = path.join(root, "loader.lua");
const toolPath = path.join(root, "toolofmind.lua");

// Set after publishing the generated core payload. The final loader always
// reads an immutable commit URL, never the moving main branch.
const PAYLOAD_COMMIT = "7d45ec0756cad4f01c7b3daad1c1b5581944472f";

function cleanLua(source) {
    return source
        .replace(/^\uFEFF/, "")
        .split(/\r?\n/)
        .filter((line) => !/^\s*--/.test(line))
        .join("\n")
        .replace(/[ \t]+$/gm, "")
        .replace(/^[ \t]+/gm, "")
        .replace(/\n{2,}/g, "\n")
        .trim();
}

function sha256(value) {
    return crypto.createHash("sha256").update(value).digest("hex");
}

const core = cleanLua(fs.readFileSync(corePath, "utf8"));
const nativeUi = cleanLua(fs.readFileSync(nativeUiPath, "utf8"));
const coreHash = sha256(core);
const nativeUiHash = sha256(nativeUi);
const coreFile = `core-${coreHash.slice(0, 20)}.lua`;

fs.mkdirSync(payloadDirectory, { recursive: true });
fs.writeFileSync(path.join(payloadDirectory, coreFile), `${core}\n`, "utf8");

const base = PAYLOAD_COMMIT
    ? `https://raw.githubusercontent.com/destr0f/toolofmind/${PAYLOAD_COMMIT}/payload/`
    : "https://raw.githubusercontent.com/destr0f/toolofmind/main/payload/";
const version = PAYLOAD_COMMIT ? "5.1.0" : "5.1.0-payload";

const template = `-- AUTO-GENERATED by build_modular.js.
-- Core SHA256: ${coreHash}
-- Embedded native UI SHA256: ${nativeUiHash}

local env=type(getgenv)=="function"and getgenv()or _G
local VERSION=${JSON.stringify(version)}
local CORE_URL=${JSON.stringify(base + coreFile)}
local CORE_SIZE=${Buffer.byteLength(core, "utf8") + 1}
local old=env.PSX_OG_LOADER_STATE
if type(old)=="table"then old.Running=false old.Superseded=true end
local state={Version=VERSION,Mode="modular-native-ui",Running=true,Ready=false,Phase="created",StartedAt=os.clock(),Trace={}}
env.PSX_OG_LOADER_STATE=state
local function persist(name,value)
 pcall(function()if type(writefile)=="function"then writefile(name,tostring(value or""))end end)
end
local function trace(phase,detail)
 state.Phase=phase
 local suffix=detail~=nil and(" | "..tostring(detail))or""
 table.insert(state.Trace,string.format("[%0.3f] %s%s",os.clock(),phase,suffix))
 print("[PSX LOADER] "..phase..suffix)
end
local function capture(problem)
 local message=tostring(problem)
 if debug and type(debug.traceback)=="function"then
  local ok,value=pcall(debug.traceback,message,2)
  if ok and value then message=value end
 end
 state.Error=message state.Phase="failed"state.Running=false
 persist("PSX_OG_loader_error.txt",table.concat(state.Trace,"\\n").."\\n\\n"..message)
 return message
end
trace("00 modular loader entered","version="..VERSION.." | source-bytes=__SOURCE_BYTES__")
local createNativeUI=(function()
${nativeUi}
end)()
trace("01 embedded UI factory ready","bytes=${Buffer.byteLength(nativeUi, "utf8")}")
local function checkReady()
 trace("02 checking game")
 local players=game:GetService("Players")
 local storage=game:GetService("ReplicatedStorage")
 local player=players.LocalPlayer
 local framework=storage:FindFirstChild("Framework")
 if not player or not player:FindFirstChild("PlayerScripts")then error("PlayerScripts is not ready; run again",0)end
 if not framework or not framework:FindFirstChild("Library")then error("Framework.Library is not ready; run again",0)end
 trace("03 game ready","place="..tostring(game.PlaceId))
end
local function downloadCore()
 trace("04 core download","expected="..CORE_SIZE)
 local ok,source=pcall(function()return game:HttpGet(CORE_URL)end)
 if not ok then error("Core download failed: "..tostring(source),0)end
 trace("05 core received","bytes="..tostring(type(source)=="string"and#source or 0))
 if type(source)~="string"or#source~=CORE_SIZE then error("Core source size mismatch",0)end
 return source
end
local function worker()
 task.wait(.1)
 trace("02 worker started")
 local ok,problem=xpcall(function()
  checkReady()
  local source=downloadCore()
  trace("06 core compiling","bytes="..#source)
  local chunk,compileError=loadstring(source)
  source=nil
  if not chunk then error("Core compile failed: "..tostring(compileError),0)end
  trace("07 core compiled")
  env.PSX_OG_NATIVE_UI_FACTORY=createNativeUI
  env.PSX_OG_TRACE_BOOT=true
  env.PSX_OG_SAFE_BOOT=true
  env.PSX_OG_SAFE_BOOT_DELAY=.02
  state.Ready=true state.Phase="core-queued"
  trace("08 core queued")
  task.defer(function(coreChunk)
   trace("09 core entered")
   local ran,runError=xpcall(coreChunk,capture)
   if not ran then
    env.PSX_OG_NATIVE_UI_FACTORY=nil
    warn("[PSX LOADER] Core failed:\\n"..tostring(runError))
    return
   end
   state.Running=false state.FinishedAt=os.clock()
   trace("10 core returned",string.format("%.2fs",state.FinishedAt-state.StartedAt))
   persist("PSX_OG_loader_trace.txt",table.concat(state.Trace,"\\n"))
  end,chunk)
  chunk=nil
 end,capture)
 if not ok then
  env.PSX_OG_NATIVE_UI_FACTORY=nil
  warn("[PSX LOADER] Startup failed:\\n"..tostring(problem))
 end
end
task.defer(worker)
return state
`;

let loader = template;
for (let pass = 0; pass < 4; pass += 1) {
    loader = template.replace("__SOURCE_BYTES__", String(Buffer.byteLength(loader, "utf8")));
}

fs.writeFileSync(loaderPath, loader, "utf8");
fs.writeFileSync(toolPath, loader, "utf8");

process.stdout.write(
    `Generated modular loader ${version}\n`
    + `  loader + embedded UI: ${Buffer.byteLength(loader, "utf8")} bytes\n`
    + `  core compile unit:     ${Buffer.byteLength(core, "utf8") + 1} bytes\n`
    + `  nested HTTP requests:  1\n`
    + `  core URL: ${base + coreFile}\n`
);
