const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const root = __dirname;
const corePath = path.join(root, "core.lua");
const nativeUiPath = path.join(root, "native_ui.lua");
const toolPath = path.join(root, "toolofmind.lua");
const loaderPath = path.join(root, "loader.lua");

function cleanLua(source) {
    return source
        .replace(/^\uFEFF/, "")
        .split(/\r?\n/)
        .filter((line) => !/^\s*--/.test(line))
        .join("\n")
        .replace(/[ \t]+$/gm, "")
        .replace(/^[ \t]+/gm, "")
        .replace(/\n{2,}/g, "\n")
        .trim();
}

function sha256(value) {
    return crypto.createHash("sha256").update(value).digest("hex");
}

const core = cleanLua(fs.readFileSync(corePath, "utf8"));
const nativeUi = cleanLua(fs.readFileSync(nativeUiPath, "utf8"));
const version = "5.0.0";

const template = `-- AUTO-GENERATED by build_standalone.js.
-- Core SHA256: ${sha256(core)}
-- Native UI SHA256: ${sha256(nativeUi)}

local __env=type(getgenv)=="function"and getgenv()or _G
local __VERSION=${JSON.stringify(version)}
local __old=__env.PSX_OG_LOADER_STATE
if type(__old)=="table"then __old.Running=false __old.Superseded=true end
local __state={Version=__VERSION,Mode="standalone-native-ui",Running=true,Ready=false,Phase="queued",StartedAt=os.clock(),Trace={}}
__env.PSX_OG_LOADER_STATE=__state
if __env.PSX_OG_TRACE_BOOT==nil then __env.PSX_OG_TRACE_BOOT=true end
if __env.PSX_OG_SAFE_BOOT==nil then __env.PSX_OG_SAFE_BOOT=true end
if __env.PSX_OG_SAFE_BOOT_DELAY==nil then __env.PSX_OG_SAFE_BOOT_DELAY=.02 end
local function __trace(phase,detail)
 __state.Phase=phase
 local suffix=detail~=nil and(" | "..tostring(detail))or""
 table.insert(__state.Trace,string.format("[%0.3f] %s%s",os.clock(),phase,suffix))
 print("[PSX ENTRY] "..phase..suffix)
end
local function __capture(problem)
 local message=tostring(problem)
 if debug and type(debug.traceback)=="function"then
  local ok,value=pcall(debug.traceback,message,2)
  if ok and value then message=value end
 end
 __state.Error=message __state.Phase="failed"__state.Running=false
 pcall(function()
  if type(writefile)=="function"then
   writefile("PSX_OG_entry_error.txt",table.concat(__state.Trace,"\\n").."\\n\\n"..message)
  end
 end)
 return message
end
local function __run()
 __trace("01 native UI factory loading")
 local createNativeUI=(function()
${nativeUi}
 end)()
 __trace("02 native UI factory ready")
${core}
 __state.Running=false __state.Ready=true __state.FinishedAt=os.clock()
 __trace("99 main returned",string.format("%.2fs",__state.FinishedAt-__state.StartedAt))
end
__trace("00 standalone entered","version="..__VERSION.." | source-bytes=__SOURCE_BYTES__")
task.defer(function()
 task.wait(.1)
 __trace("00 worker started")
 local ok,problem=xpcall(__run,__capture)
 if not ok then warn("[PSX ENTRY] Startup failed:\\n"..tostring(problem))end
end)
return __state
`;

let standalone = template;
for (let pass = 0; pass < 4; pass += 1) {
    standalone = template.replace("__SOURCE_BYTES__", String(Buffer.byteLength(standalone, "utf8")));
}

fs.writeFileSync(toolPath, standalone, "utf8");
fs.writeFileSync(loaderPath, standalone, "utf8");

process.stdout.write(
    `Generated standalone English build ${version}\n`
    + `  core:      ${Buffer.byteLength(core, "utf8")} bytes\n`
    + `  native UI: ${Buffer.byteLength(nativeUi, "utf8")} bytes\n`
    + `  release:   ${Buffer.byteLength(standalone, "utf8")} bytes\n`
    + `  requests after entry: 0\n`
);
