const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const root = __dirname;
const mainPath = path.join(root, "toolofmind.lua");
const windPath = path.join(root, "vendor", "WindUI-1.6.64-fix.lua");
const loaderPath = path.join(root, "loader.lua");
const mainSource = fs.readFileSync(mainPath, "utf8").replace(/^\uFEFF/, "");
const windVendorSource = fs.readFileSync(windPath, "utf8").replace(/^\uFEFF/, "");
const windSource = windVendorSource.replace(
    "if d:IsStudio()or not writefile then",
    "if true then -- standalone bundle: use the embedded icon pack"
);
if (windSource === windVendorSource) {
    throw new Error("WindUI icon-loader patch point was not found");
}
const mainHash = crypto.createHash("sha256").update(mainSource).digest("hex");
const windVendorHash = crypto.createHash("sha256").update(windVendorSource).digest("hex");
const windHash = crypto.createHash("sha256").update(windSource).digest("hex");

const prelude = String.raw`-- AUTO-GENERATED by build_loader.js. Do not edit loader.lua directly.
-- Main SHA256: ${mainHash}
-- WindUI 1.6.64-fix vendor SHA256: ${windVendorHash}
-- WindUI bundled SHA256: ${windHash}
-- PSX OG standalone loader: one HTTP request, deferred main execution.

local __psxEnv = type(getgenv) == "function" and getgenv() or _G
local __PSX_BUNDLE_VERSION = "2.1.0"
local __PSX_TRACE_FILE = "PSX_OG_loader_trace.txt"
local __PSX_ERROR_FILE = "PSX_OG_loader_error.txt"

local __psxPreviousState = __psxEnv.PSX_OG_LOADER_STATE
if type(__psxPreviousState) == "table"
    and __psxPreviousState.Running == true
    and os.clock() - (tonumber(__psxPreviousState.StartedAt) or 0) < 60 then
    warn("[PSX LOADER] A loader run is already in progress: " .. tostring(__psxPreviousState.Phase))
    return __psxPreviousState
end

local __psxState = {
    Version = __PSX_BUNDLE_VERSION,
    Mode = "standalone",
    Running = true,
    Ready = false,
    Phase = "created",
    StartedAt = os.clock(),
    Trace = {}
}
__psxEnv.PSX_OG_LOADER_STATE = __psxState

local function __psxPersist(name, contents)
    pcall(function()
        if type(writefile) == "function" then
            writefile(name, tostring(contents or ""))
        end
    end)
end

local function __psxTrace(phase, detail)
    __psxState.Phase = phase
    local suffix = detail ~= nil and (" | " .. tostring(detail)) or ""
    local line = string.format("[%0.3f] %s%s", os.clock(), tostring(phase), suffix)
    table.insert(__psxState.Trace, line)
    __psxPersist(__PSX_TRACE_FILE, table.concat(__psxState.Trace, "\n"))
    print("[PSX LOADER] " .. tostring(phase) .. suffix)
end

local function __psxCaptureError(problem)
    local message = tostring(problem)
    if debug and type(debug.traceback) == "function" then
        local success, traceback = pcall(debug.traceback, message, 2)
        if success and traceback then message = traceback end
    end
    __psxState.Error = message
    __psxState.Phase = "failed"
    __psxState.Running = false
    __psxPersist(__PSX_ERROR_FILE, message)
    return message
end

local function __psxWaitForGameReady()
    __psxTrace("01 waiting for game")
    local loaded = false
    pcall(function() loaded = game:IsLoaded() end)
    if not loaded then game.Loaded:Wait() end

    local Players = game:GetService("Players")
    local ReplicatedStorage = game:GetService("ReplicatedStorage")
    local RunService = game:GetService("RunService")
    local deadline = os.clock() + 30
    local player = Players.LocalPlayer
    while not player and os.clock() < deadline do
        task.wait(0.05)
        player = Players.LocalPlayer
    end
    if not player then error("LocalPlayer did not appear within 30 seconds", 0) end

    local playerScripts = player:FindFirstChild("PlayerScripts")
        or player:WaitForChild("PlayerScripts", 20)
    if not playerScripts then error("PlayerScripts did not load", 0) end

    local framework = ReplicatedStorage:FindFirstChild("Framework")
        or ReplicatedStorage:WaitForChild("Framework", 20)
    local library = framework and (
        framework:FindFirstChild("Library")
        or framework:WaitForChild("Library", 20)
    )
    if not library then error("ReplicatedStorage.Framework.Library did not load", 0) end

    for _ = 1, 3 do RunService.Heartbeat:Wait() end
    __psxTrace("02 game ready", "place=" .. tostring(game.PlaceId))
end

__psxEnv.PSX_OG_TRACE_BOOT = true
__psxEnv.PSX_OG_SAFE_BOOT = true
__psxEnv.PSX_OG_SAFE_BOOT_DELAY = math.clamp(
    tonumber(__psxEnv.PSX_OG_SAFE_BOOT_DELAY) or 0.03,
    0.01,
    0.25
)

local function __psxBundledWindUI(...)
-- BEGIN BUNDLED WINDUI
`;

const bridge = String.raw`
-- END BUNDLED WINDUI
end

__psxEnv.PSX_OG_BUNDLED_WINDUI_CHUNK = __psxBundledWindUI

local function __psxBundledMain(...)
-- BEGIN BUNDLED MAIN
`;

const suffix = String.raw`
-- END BUNDLED MAIN
end

__psxState.Phase = "scheduled"
__psxTrace("00 standalone loader entered", "version=" .. __PSX_BUNDLE_VERSION)

task.defer(function()
    task.wait(0.15)

    local success, problem = xpcall(function()
        __psxWaitForGameReady()
        __psxTrace("03 executing bundled main")
        __psxState.Result = __psxBundledMain()
        __psxState.Running = false
        __psxState.Ready = true
        __psxState.FinishedAt = os.clock()
        __psxTrace(
            "04 main returned",
            string.format("%.2fs", __psxState.FinishedAt - __psxState.StartedAt)
        )
    end, __psxCaptureError)

    if not success then
        warn("[PSX LOADER] Startup failed:\n" .. tostring(problem))
    end
end)

return __psxState
`;

const output = prelude + windSource + bridge + mainSource + suffix;
fs.writeFileSync(loaderPath, output, "utf8");
process.stdout.write(
    `Generated loader.lua (${Buffer.byteLength(output, "utf8")} bytes) `
    + `from main=${mainHash} windui=${windHash}\n`
);
