-- AUTO-GENERATED by build_staged_loader.js.
-- Main source SHA256: 42cb3ef0219d23c2ee401947b59e6db32efc8f0f91e92d020d64560201e92631
-- Main bundled SHA256: c85d75e22a0ae2eaa9cc397a6814d3259c936b03492384fae24e16ff9f52c866
-- WindUI vendor SHA256: 6b0129924f67ef979559bd87a43eb05ac74e927d9ca56fefd9398ef8316ea4e8
-- WindUI bundled SHA256: e8b69bf934fd71ef334c5486218bef9a993564f17328aae78b09988febfc0923

local env=type(getgenv)=="function"and getgenv()or _G
local VERSION="4.0.1"
local BASE=tostring(env.PSX_OG_PAYLOAD_BASE_URL or"https://raw.githubusercontent.com/destr0f/toolofmind/main/payload/")
local MAIN_RAW=139648
local MAIN_PACKED=35586
local WIND_RAW=254933
local WIND_PACKED=72858
local MAIN_PARTS={
    {
        File = "main-c85d75e22a0ae2eaa9cc-01-16a27758402d.psx",
        PackedSize = 16384,
        EncodedChars = 20480
    },
    {
        File = "main-c85d75e22a0ae2eaa9cc-02-a64bbbc8cbf2.psx",
        PackedSize = 16384,
        EncodedChars = 20480
    },
    {
        File = "main-c85d75e22a0ae2eaa9cc-03-77f28517a4ba.psx",
        PackedSize = 2818,
        EncodedChars = 3525
    }
}
local WIND_PARTS={
    {
        File = "wind-e8b69bf934fd71ef334c-01-7099c3ad0dd3.psx",
        PackedSize = 16384,
        EncodedChars = 20480
    },
    {
        File = "wind-e8b69bf934fd71ef334c-02-c664e3b014a5.psx",
        PackedSize = 16384,
        EncodedChars = 20480
    },
    {
        File = "wind-e8b69bf934fd71ef334c-03-f459a595fbbd.psx",
        PackedSize = 16384,
        EncodedChars = 20480
    },
    {
        File = "wind-e8b69bf934fd71ef334c-04-a9793bfa4082.psx",
        PackedSize = 16384,
        EncodedChars = 20480
    },
    {
        File = "wind-e8b69bf934fd71ef334c-05-2e365c033f89.psx",
        PackedSize = 7322,
        EncodedChars = 9155
    }
}

local old=env.PSX_OG_LOADER_STATE
if type(old)=="table"then old.Running=false old.Superseded=true end
local state={Version=VERSION,Mode="staged-cache",Running=true,Ready=false,Phase="created",StartedAt=os.clock(),Trace={}}
env.PSX_OG_LOADER_STATE=state

local function persist(name,value)
 pcall(function()if type(writefile)=="function"then writefile(name,tostring(value or""))end end)
end
local function trace(phase,detail)
 state.Phase=phase
 local suffix=detail~=nil and(" | "..tostring(detail))or""
 table.insert(state.Trace,string.format("[%0.3f] %s%s",os.clock(),phase,suffix))
 print("[PSX LOADER] "..phase..suffix)
end
local function capture(problem)
 local message=tostring(problem)
 if debug and type(debug.traceback)=="function"then
  local ok,value=pcall(debug.traceback,message,2)
  if ok and value then message=value end
 end
 state.Error=message state.Phase="failed"state.Running=false
 persist("PSX_OG_loader_error.txt",table.concat(state.Trace,"\n").."\n\n"..message)
 return message
end
local function checkReady()
 trace("01 checking game")
 local players=game:GetService("Players")
 local storage=game:GetService("ReplicatedStorage")
 local player=players.LocalPlayer
 local framework=storage:FindFirstChild("Framework")
 if not player or not player:FindFirstChild("PlayerScripts")then error("PlayerScripts is not ready; run again",0)end
 if not framework or not framework:FindFirstChild("Library")then error("Framework.Library is not ready; run again",0)end
 trace("02 game ready","place="..tostring(game.PlaceId))
end
local function cacheName(part)return"PSX_OG_payload_"..part.File end
local function valid(data,part)
 return type(data)=="string"and#data>=part.EncodedChars and not string.find(data,"<!DOCTYPE html",1,true)
end
local function readCache(part)
 if type(readfile)~="function"then return nil end
 local ok,data=pcall(readfile,cacheName(part))
 if ok and valid(data,part)then return data end
 return nil
end
local function cachePart(part,index,total,kind)
 local data=readCache(part)
 if data then trace("03 payload cached",kind.." "..index.."/"..total)return end
 trace("03 payload download",kind.." "..index.."/"..total)
 local ok,response=pcall(function()return game:HttpGet(BASE..part.File)end)
 if not ok then error("Payload download failed: "..tostring(response),0)end
 if not valid(response,part)then error("Invalid payload response: "..part.File,0)end
 writefile(cacheName(part),response)
 trace("03 payload saved",kind.." "..index.."/"..total)
end
local function prepare(parts,kind)
 for index,part in ipairs(parts)do
  if env.PSX_OG_LOADER_STATE~=state then error("Loader superseded",0)end
  cachePart(part,index,#parts,kind)
 end
end

local alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#$%&()*+,-./:;<=>?@^_`"
local decode={}
for index=1,#alphabet do decode[string.byte(alphabet,index)]=index-1 end
local function decodeInto(data,output,offset,expected)
 local position,accumulator,digits=0,0,0
 for index=1,#data do
  local value=decode[string.byte(data,index)]
  if value~=nil then
   accumulator=accumulator*85+value digits=digits+1
   if digits==5 then
    for shift=3,0,-1 do
     if position<expected then
      buffer.writeu8(output,offset+position,math.floor(accumulator/(256^shift))%256)
      position=position+1
     end
    end
    accumulator=0 digits=0
   end
  end
 end
 if position~=expected then error("Base85 cached payload length mismatch",0)end
end
local function readPacked(parts,size,kind)
 local output=buffer.create(size)
 local offset=0
 for index,part in ipairs(parts)do
  trace("04 payload decode",kind.." "..index.."/"..#parts)
  local data=readCache(part)
  if not data then error("Cached payload missing: "..part.File,0)end
  decodeInto(data,output,offset,part.PackedSize)
  data=nil offset=offset+part.PackedSize
 end
 if offset~=size then error("Packed payload size mismatch",0)end
 return output
end
local function decompress(input,inputLength,expected)
 local output=buffer.create(expected)
 local inputPosition,outputPosition=0,0
 while inputPosition<inputLength do
  local token=buffer.readu8(input,inputPosition)inputPosition=inputPosition+1
  if token<128 then
   local length=token+1
   if inputPosition+length>inputLength or outputPosition+length>expected then error("Invalid literal run",0)end
   buffer.copy(output,outputPosition,input,inputPosition,length)
   inputPosition=inputPosition+length outputPosition=outputPosition+length
  else
   local length=token-128+3
   if inputPosition+2>inputLength then error("Truncated back-reference",0)end
   local distance=buffer.readu8(input,inputPosition)+buffer.readu8(input,inputPosition+1)*256
   inputPosition=inputPosition+2
   if distance<1 or distance>outputPosition or outputPosition+length>expected then error("Invalid back-reference",0)end
   local source=outputPosition-distance
   local available,remaining=distance,length
   while remaining>0 do
    local count=math.min(available,remaining)
    buffer.copy(output,outputPosition,output,source,count)
    outputPosition=outputPosition+count remaining=remaining-count available=available+count
   end
  end
 end
 if outputPosition~=expected then error("LZSS output size mismatch",0)end
 return output
end
local function compilePayload(parts,packedSize,rawSize,kind)
 trace("05 assembling",kind)
 local packed=readPacked(parts,packedSize,kind)
 trace("06 decompressing",kind.." | raw="..rawSize)
 local raw=decompress(packed,packedSize,rawSize)packed=nil
 trace("07 creating source",kind)
 local source=buffer.tostring(raw)raw=nil
 trace("08 compiling",kind.." | bytes="..#source)
 local chunk,problem=loadstring(source)source=nil
 if not chunk then error(kind.." compile failed: "..tostring(problem),0)end
 trace("09 compiled",kind)
 return chunk
end
local function run()
 checkReady()
 if type(buffer)~="table"or type(buffer.create)~="function"then error("Roblox buffer library required",0)end
 if type(readfile)~="function"or type(writefile)~="function"then error("readfile/writefile required",0)end
 env.PSX_OG_TRACE_BOOT=true env.PSX_OG_SAFE_BOOT=true
 env.PSX_OG_SAFE_BOOT_DELAY=math.clamp(tonumber(env.PSX_OG_SAFE_BOOT_DELAY)or.03,.01,.25)
 trace("03 preparing payload cache","parts="..tostring(#MAIN_PARTS+#WIND_PARTS))
 prepare(MAIN_PARTS,"Main")prepare(WIND_PARTS,"WindUI")
 trace("03 payload cache ready")
 local mainChunk=compilePayload(MAIN_PARTS,MAIN_PACKED,MAIN_RAW,"Main")MAIN_PARTS=nil
 local windChunk=compilePayload(WIND_PARTS,WIND_PACKED,WIND_RAW,"WindUI")WIND_PARTS=nil
 env.PSX_OG_BUNDLED_WINDUI_CHUNK=windChunk windChunk=nil
 state.Running=false state.Ready=true state.FinishedAt=os.clock()
 task.defer(mainChunk)mainChunk=nil
 trace("10 main queued; staged loader releasing",string.format("%.2fs",state.FinishedAt-state.StartedAt))
 persist("PSX_OG_loader_trace.txt",table.concat(state.Trace,"\n"))
end
local function worker()
 task.wait(.15)
 trace("00 worker started")
 local ok,problem=xpcall(run,capture)
 if not ok then env.PSX_OG_BUNDLED_WINDUI_CHUNK=nil warn("[PSX LOADER] Startup failed:\n"..tostring(problem))end
end
trace("00 staged loader entered","version="..VERSION.." | source-bytes=9002")
state.Phase="queued"
task.defer(worker)
return state
