-- AUTO-GENERATED by build_binary_loader.js.
-- Main source SHA256: 42cb3ef0219d23c2ee401947b59e6db32efc8f0f91e92d020d64560201e92631
-- Main bundled SHA256: c85d75e22a0ae2eaa9cc397a6814d3259c936b03492384fae24e16ff9f52c866
-- WindUI vendor SHA256: 6b0129924f67ef979559bd87a43eb05ac74e927d9ca56fefd9398ef8316ea4e8
-- WindUI bundled SHA256: 6cbaf0350fc5550eff5dd9fb8eb9545b12c40fce40365db73cbd7a0e1744d1f8

local env=type(getgenv)=="function"and getgenv()or _G
local VERSION="4.1.1-payload"
local BASE=tostring(env.PSX_OG_PAYLOAD_BASE_URL or "https://raw.githubusercontent.com/destr0f/toolofmind/main/payload/")
local MAIN={Parts={{File="main-c85d75e22a0ae2eaa9cc-22cf456ce330.bin",Size=35586}},Packed=35586,Raw=139648}
local WIND={Parts={{File="wind-6cbaf0350fc5550eff5d-01-fe4e0b3e95fc.bin",Size=24576},{File="wind-6cbaf0350fc5550eff5d-02-b593c0eb4817.bin",Size=24576},{File="wind-6cbaf0350fc5550eff5d-03-21d4b4e8fff4.bin",Size=23706}},Packed=72858,Raw=254933}

local old=env.PSX_OG_LOADER_STATE
if type(old)=="table"then old.Running=false old.Superseded=true end
local state={Version=VERSION,Mode="binary-cache",Running=true,Ready=false,Phase="created",StartedAt=os.clock(),Trace={}}
env.PSX_OG_LOADER_STATE=state

local function persist(name,value)
 pcall(function()if type(writefile)=="function"then writefile(name,tostring(value or""))end end)
end
local function trace(phase,detail)
 state.Phase=phase
 local suffix=detail~=nil and(" | "..tostring(detail))or""
 table.insert(state.Trace,string.format("[%0.3f] %s%s",os.clock(),phase,suffix))
 print("[PSX LOADER] "..phase..suffix)
end
local function capture(problem)
 local message=tostring(problem)
 if debug and type(debug.traceback)=="function"then
  local ok,value=pcall(debug.traceback,message,2)
  if ok and value then message=value end
 end
 state.Error=message state.Phase="failed"state.Running=false
 persist("PSX_OG_loader_error.txt",table.concat(state.Trace,"\n").."\n\n"..message)
 return message
end
local function checkReady()
 trace("01 checking game")
 local players=game:GetService("Players")
 local storage=game:GetService("ReplicatedStorage")
 local player=players.LocalPlayer
 local framework=storage:FindFirstChild("Framework")
 if not player or not player:FindFirstChild("PlayerScripts")then error("PlayerScripts is not ready; run again",0)end
 if not framework or not framework:FindFirstChild("Library")then error("Framework.Library is not ready; run again",0)end
 trace("02 game ready","place="..tostring(game.PlaceId))
end
local function cacheName(part)return"PSX_OG_payload_"..part.File end
local function readCache(part)
 local ok,data=pcall(readfile,cacheName(part))
 if ok and type(data)=="string"and#data==part.Size then return data end
 return nil
end
local function cachePayload(item,kind)
 for index,part in ipairs(item.Parts)do
  local label=kind.." "..index.."/"..#item.Parts
  local data=readCache(part)
  if data then
   trace("03 binary cached",label.." | bytes="..#data)
  else
   trace("03 binary download",label.." | expected="..part.Size)
   local ok,response=pcall(function()return game:HttpGet(BASE..part.File)end)
   if not ok then error(label.." download failed: "..tostring(response),0)end
   trace("03 binary received",label.." | bytes="..tostring(type(response)=="string"and#response or 0))
   if type(response)~="string"or#response~=part.Size then error(label.." binary size mismatch",0)end
   trace("03 binary writing",label)
   local wrote,writeError=pcall(writefile,cacheName(part),response)
   if not wrote then error(label.." cache write failed: "..tostring(writeError),0)end
   trace("03 binary saved",label)
  end
  data=nil
  if index<#item.Parts then task.wait(.15)end
 end
end
local function toBuffer(data)
 if type(buffer.fromstring)=="function"then return buffer.fromstring(data)end
 local output=buffer.create(#data)
 if type(buffer.writestring)~="function"then error("buffer.fromstring or buffer.writestring required",0)end
 buffer.writestring(output,0,data)
 return output
end
local function readPacked(item,kind)
 local output=buffer.create(item.Packed)
 local offset=0
 for index,part in ipairs(item.Parts)do
  trace("04 binary reading",kind.." "..index.."/"..#item.Parts)
  local data=readCache(part)
  if not data then error(kind.." binary cache missing: "..part.File,0)end
  local source=toBuffer(data)data=nil
  buffer.copy(output,offset,source,0,part.Size)
  source=nil offset=offset+part.Size
 end
 if offset~=item.Packed then error(kind.." assembled binary size mismatch",0)end
 return output
end
local function decompress(input,inputLength,expected)
 local output=buffer.create(expected)
 local inputPosition,outputPosition=0,0
 while inputPosition<inputLength do
  local token=buffer.readu8(input,inputPosition)inputPosition=inputPosition+1
  if token<128 then
   local length=token+1
   if inputPosition+length>inputLength or outputPosition+length>expected then error("Invalid literal run",0)end
   buffer.copy(output,outputPosition,input,inputPosition,length)
   inputPosition=inputPosition+length outputPosition=outputPosition+length
  else
   local length=token-128+3
   if inputPosition+2>inputLength then error("Truncated back-reference",0)end
   local distance=buffer.readu8(input,inputPosition)+buffer.readu8(input,inputPosition+1)*256
   inputPosition=inputPosition+2
   if distance<1 or distance>outputPosition or outputPosition+length>expected then error("Invalid back-reference",0)end
   local source=outputPosition-distance
   local available,remaining=distance,length
   while remaining>0 do
    local count=math.min(available,remaining)
    buffer.copy(output,outputPosition,output,source,count)
    outputPosition=outputPosition+count remaining=remaining-count available=available+count
   end
  end
 end
 if outputPosition~=expected then error("LZSS output size mismatch",0)end
 return output
end
local function compilePayload(item,kind)
 local packed=readPacked(item,kind)
 trace("05 decompressing",kind.." | raw="..item.Raw)
 local raw=decompress(packed,item.Packed,item.Raw)packed=nil
 trace("06 creating source",kind)
 local source=buffer.tostring(raw)raw=nil
 trace("07 compiling",kind.." | bytes="..#source)
 local chunk,problem=loadstring(source)source=nil
 if not chunk then error(kind.." compile failed: "..tostring(problem),0)end
 trace("08 compiled",kind)
 return chunk
end
local function run()
 checkReady()
 if type(buffer)~="table"or type(buffer.create)~="function"then error("Roblox buffer library required",0)end
 if type(readfile)~="function"or type(writefile)~="function"then error("readfile/writefile required",0)end
 env.PSX_OG_TRACE_BOOT=true env.PSX_OG_SAFE_BOOT=true
 env.PSX_OG_SAFE_BOOT_DELAY=math.clamp(tonumber(env.PSX_OG_SAFE_BOOT_DELAY)or.03,.01,.25)
 trace("03 preparing binary cache","requests="..tostring(#MAIN.Parts+#WIND.Parts))
 cachePayload(MAIN,"Main")
 task.wait(.2)
 cachePayload(WIND,"WindUI")
 trace("03 binary cache ready")
 local mainChunk=compilePayload(MAIN,"Main")MAIN=nil
 local windChunk=compilePayload(WIND,"WindUI")WIND=nil
 env.PSX_OG_BUNDLED_WINDUI_CHUNK=windChunk windChunk=nil
 state.Running=false state.Ready=true state.FinishedAt=os.clock()
 task.defer(mainChunk)mainChunk=nil
 trace("09 main queued; binary loader releasing",string.format("%.2fs",state.FinishedAt-state.StartedAt))
 persist("PSX_OG_loader_trace.txt",table.concat(state.Trace,"\n"))
end
local function worker()
 task.wait(.15)
 trace("00 worker started")
 local ok,problem=xpcall(run,capture)
 if not ok then env.PSX_OG_BUNDLED_WINDUI_CHUNK=nil warn("[PSX LOADER] Startup failed:\n"..tostring(problem))end
end
trace("00 binary loader entered","version="..VERSION.." | source-bytes=7710")
state.Phase="queued"
task.defer(worker)
return state
